name = "RotA-SERVER"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3a7bdf04a4209b5eebc7fc4cd2bae92f6d56ba7ac1f0b69d294dda62ac211bd"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
