name = "RotA-SERVER"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ce2e1fccc3febbfb88d3f20c21ca498b979e801d09b8d9caf8ca1fcc2e3c6e1"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
