name = "RotA-SERVER"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2dfb6fbadb9aba8e2effcfa5ca795eb569cc1f745df1c1dc8f9a810705fd867"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
