name = "RotA-SERVER"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be2fa95fe16baf76eaa0b98501fc0509a96a0afba0fa30b235d9cace973b0611"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
