name = "RotA-SERVER"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e31cd397aa78fab4e7fb9e6e5940c3ae88edd322afaed76527eaed62ce2b6c35"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
