name = "RotA-SERVER"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b3fc7d2844ce5e17ea37f6fd65221f188ae9f45d43babea69cf019abd82d9ec"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
