name = "RotA-SERVER"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5dc6ec2fa9f663dc1e1bdb38e4bccd992be56ef40ad1e4888e9f02ee7a59451e"

[versions]
forge = "14.23.5.2854"
minecraft = "1.12.2"
