name = "Additional Lights"
filename = "additional_lights-1.12.2-1.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2989/463/additional_lights-1.12.2-1.2.1.jar"
hash-format = "murmur2"
hash = "3988870341"

[update]
[update.curseforge]
file-id = 2989463
project-id = 384991
release-channel = "beta"
